[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
bytes = "1.3.0"
ciborium = "0.2.0"
ron = "0.8.0"
serde = { version = "1.0.147", features = ["derive"] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }

